/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unicahccpmp.universidades;
import com.unicahccpmp.dao.Universidad;
import com.unicahccpmp.dao.UniversidadModel;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author carlospineda
 */
public class UniversidadForm extends javax.swing.JDialog {
    private Universidad currentUniversidad;
    private boolean _reloadParent = false;
    private String _mode;
    
    public boolean getReloadParent(){
        return _reloadParent;
    }
    /**
     * Creates new form UniversidadForm
     */
    public UniversidadForm(String Mode, double id) {

        initComponents();
        setModal(true);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        
        // INS, UPD, DEL, DSP
        _mode = Mode;
        if (!Mode.equals("INS")){
            //No es un insert por tando debe existir en la DB
            //Proceso para capturar el Registro
            System.out.println(id);
            currentUniversidad = UniversidadModel.getUniversidadesById(id);
            jTSiglas.setText(currentUniversidad.getSIGLAS());
            jTRector.setText(currentUniversidad.getRECTOR());
        }else {
            currentUniversidad = new Universidad();
        }
        switch(Mode){
            case "INS":
                jLTitle.setText("Agregando nueva Universidad");
                jBConfirmar.setText("Agregar");
                break;
            case "UPD":
                jLTitle.setText(String.format("Actualizando Universidad %.0f %s", currentUniversidad.getID(), currentUniversidad.getSIGLAS()));
                jBConfirmar.setText("Editar");
                break;
            case "DEL":
                jLTitle.setText(String.format("Eliminar Universidad %.0f %s", currentUniversidad.getID(), currentUniversidad.getSIGLAS()));
                deshabilitarCampos();
                jBConfirmar.setText("Eliminar");
                break;
            case "DSP":
                jBConfirmar.setVisible(false);
                jBCancel.setText("Salir");
                deshabilitarCampos();
                jLTitle.setText(String.format("Universidad %.0f %s", currentUniversidad.getID(), currentUniversidad.getSIGLAS()));
                break;
        }
    }
    
    private void deshabilitarCampos(){
         jTSiglas.setEditable(false);
         jTRector.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTRector = new javax.swing.JTextField();
        jTSiglas = new javax.swing.JTextField();
        jBConfirmar = new javax.swing.JButton();
        jBCancel = new javax.swing.JButton();

        jLTitle.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLTitle.setText("Universidad");

        jLabel1.setText("Siglas");

        jLabel2.setText("Rector");

        jTSiglas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTSiglasActionPerformed(evt);
            }
        });

        jBConfirmar.setText("jButton1");
        jBConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBConfirmarMouseClicked(evt);
            }
        });
        jBConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConfirmarActionPerformed(evt);
            }
        });

        jBCancel.setText("Cancelar");
        jBCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBCancelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jBConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jBCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTRector, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTSiglas, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLTitle)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addComponent(jTSiglas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addComponent(jTRector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBConfirmar)
                    .addComponent(jBCancel)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBConfirmarMouseClicked
        // TODO add your handling code here:
        currentUniversidad.setSIGLAS(jTSiglas.getText());
        currentUniversidad.setRECTOR(jTRector.getText());
        
        
        //Validaciones Expresiones Regulares
        
        switch(_mode){
            case "INS":
                _reloadParent = UniversidadModel.agregarUniversidad(currentUniversidad);
                break;
            case "UPD":
                _reloadParent = UniversidadModel.editarUniversidad(currentUniversidad);
                break;
            case "DEL":
                _reloadParent = UniversidadModel.eliminarUniversidad(currentUniversidad);
                break;
        }
        
        dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_jBConfirmarMouseClicked

    private void jBCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCancelMouseClicked
        // TODO add your handling code here:
        _reloadParent = false;
        dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_jBCancelMouseClicked

    private void jTSiglasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTSiglasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTSiglasActionPerformed

    private void jBConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBConfirmarActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancel;
    private javax.swing.JButton jBConfirmar;
    private javax.swing.JLabel jLTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTRector;
    private javax.swing.JTextField jTSiglas;
    // End of variables declaration//GEN-END:variables
}
